### ISSUE TITLE
required eigen version on Ros melodic

### ISSUE THREAD

**Issue by ebimor** [stonier/ecl_core#110]
Hi there, 

On linux 18.04 and ROS melodic, I have a lot of problems with including the ecl headers (specifically ecl_geometry) and the errora that I receive are related to eigen (it's a long list of errors so I don't copy them here). I resolved the issue by downgrading the version of eigen on my system to 3.2.1. Strangely, I can compile everything without any problem on Linux 16.04 and ROS kinetic and eigen version 3.3~beta1-2. So I am not sure what is causing this problem. Is there a way to resolve this without changing Linux eigen version? Any help/hint would be greatly appreciated.

Thanks
[eigen erros.log](https://github.com/stonier/ecl_core/files/5496272/eigen.erros.log)

**Comment by eshahrivar-cpr** [comment]
Closing here. It was a linking problem on my side.

**Comment by ebimor** [comment]
Closing this issue here. It was a linking issue on my side.
