### ISSUE TITLE
Returning local variable from what() member of StandardException and DataException

### ISSUE THREAD

**Issue by yichoe** [stonier/ecl_core#15]
what() members of StandardException and DataException return pointer to string which is created locally. Therefore we can't expect what we'll get from calling.

It need to make what() return basic_string instance as it is or make its instance static.

**Comment by stonier** [comment]
Ah, this might explain the problem I had with it for a long time. On windows it sometimes shows the what(), other times it showed nothing.

Where in the code are you looking at?

**Comment by yichoe** [comment]
Maybe I forgot :-) I'm looking at ecl_core/ecl_exceptions in win_porting branch.
