### ISSUE TITLE
ecl_core/ecl_threads

### ISSUE THREAD

**Issue by jakan2** [stonier/ecl_core#2]
During the release mode compilation, it shown me

/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp: In function ‘bool ecl::set_priority(ecl::Priority)’:
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp:115:9: error: ‘throwPriorityException’ is not a member of ‘ecl::threads’
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp: In function ‘ecl::Priority ecl::get_priority()’:
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp:130:17: error: ‘throwPriorityException’ is not a member of ‘ecl::threads’
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp:144:21: error: ‘throwPriorityException’ is not a member of ‘ecl::threads’
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp: In function ‘std::string ecl::print_priority_diagnostics()’:
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp:217:5: error: ‘throwPriorityException’ is not a member of ‘ecl::threads’
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp: In function ‘bool ecl::threads::set_real_time_priority(int, int)’:
/mnt/data/cslam_catkin/src/ecl_core/ecl_threads/src/lib/priority_pos.cpp:326:4: error: ‘throwPriorityException’ was not declared in this scope
make[3]: **\* [ecl_core/ecl_threads/src/lib/CMakeFiles/ecl_threads.dir/priority_pos.cpp.o] Error 1

**Comment by stonier** [comment]
Fixed, along with some other minor bugs.
