### ISSUE TITLE
Linking error on Kobuki driver test programs

### ISSUE THREAD

**Issue by corot** [stonier/ecl_core#25]
```
Linking CXX executable ../../../../devel/lib/kobuki_driver/demo_kobuki_initialisation
../../../../devel/lib/libkobuki.so: undefined reference to `ecl::SigSlot<ecl::Void>::emit()'
../../../../devel/lib/libkobuki.so: undefined reference to `ecl::SigSlot<ecl::Void>::connectSignal(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../../../devel/lib/libkobuki.so: undefined reference to `ecl::SigSlot<ecl::Void>::~SigSlot()'
```

**Comment by stonier** [comment]
Odd, works for me.  Exactly what version of kobuki and ecl are you compiling against?

for me:
- ecl: latest groovy-devel
- kobuki: latest groovy-devel

**Comment by corot** [comment]
same.  But remember I compile without calling catkin nor yujin tools

  cd ~/kobuki_ws/build
  KOBUKI_DRIVER_LOCATION=../install
  KOBUKI_DRIVER_PACKAGES="`sed -n -e ":a" -e "$ s/\n/;/gp;N;b a" ../src/kobuki/kobuki_driver/catkin_whitelist`"
  cmake ../src -DCATKIN_WHITELIST_PACKAGES=$KOBUKI_DRIVER_PACKAGES -DCMAKE_INSTALL_PREFIX=$KOBUKI_DRIVER_LOCATION
  make

**Comment by corot** [comment]
Somehow I was linking against groovy installed libraries instead of against the newly compiled.
Removing ros-groovy-ecl-xxxx clean-make again fixed the problem.
