### ISSUE TITLE
ecl_thread: fails to configure - missing ecl_detect_threads

### ISSUE THREAD

**Issue by dirk-thomas** [stonier/ecl_core#32]
It looks like `ecl_build` does not export it correctly.

See failing CI job: http://jenkins.ros.org/job/devel-hydro-ecl_core/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/2/console

**Comment by dirk-thomas** [comment]
Same for `ecl_lite` using `ecl_detect_platform`: http://jenkins.ros.org/view/Hdev/job/devel-hydro-ecl_lite/3/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/console

**Comment by stonier** [comment]
Looks like I already updated for this six months ago in https://github.com/stonier/ecl_tools/commit/8749515b2f3e3aa2231079397fae33744b0302e7 and 72f2184219e82b6f9855f7a3367a3d44f335e910 but never released.  Just released, but will wait on closing this for success.

**Comment by dirk-thomas** [comment]
Looks like the jobs hit the next error now: http://jenkins.ros.org/job/devel-hydro-ecl_core/4/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/console

**Comment by stonier** [comment]
export the configured header like roscpp does - 110a815a17e341859dac1f22498205100ae6fcf9

**Comment by dirk-thomas** [comment]
Different error but still failing: http://jenkins.ros.org/job/devel-hydro-ecl_core/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/8/console

**Comment by dirk-thomas** [comment]
Succeeded.
