### ISSUE TITLE
Utility : quaternion2yaw

### ISSUE THREAD

**Issue by stonier** [stonier/ecl_core#40]
Wanted!

**Comment by vrabaud** [comment]
Your implementation does not take into account the gimbal lock. You should probably use:
https://github.com/ros/geometry_experimental/blob/indigo-devel/tf2/include/tf2/impl/utils.h#L123
(not yet released but in master ...)

**Comment by stonier** [comment]
You have too much spare time vincent! :neckbeard:

Thanks for the pointer! Was just a simple utility we can put on the arm board, but good to have it corrected so I don't copy a bad calculation later.
