### ISSUE TITLE
First use of serial device throws "device already locked" exception 

### ISSUE THREAD

**Issue by bit-pirate** [stonier/ecl_core#41]
After (re-)starting the machine, the first attempt of use a serial device throws this exception: https://github.com/stonier/ecl_core/blob/1337f3db4812031fd18dafab58820fd2b444e9d3/ecl_devices/src/lib/serial_pos.cpp#L145

On the second attempt (restarting the process (not the machine) using the serial device) it works.

@alexreimann is this the error (exception) you have been seeing, when you said "you have to start minimal twice"?

**Comment by AlexReimann** [comment]
Nope, what i meant was that some nodes of minimal go down and the robot is
not driveable

**Comment by stonier** [comment]
Let me know what errno. shows if you see it - we can look up the man page for `fcnt` to get the hint.

**Comment by AlexReimann** [comment]
It doesn't give an error code, it is just some ros nodes dying (during 
the start of minimal).
On the second try everything works fine. Sometimes everything works on 
the first try (2 or 3 times out of 50).

I actually never saw it happen on gocart 1.1.
There was no time for me to further investigate on wednesday because the 
reliability test had priority.

Am 02.01.2015 um 23:05 schrieb Daniel Stonier:

**Comment by bit-pirate** [comment]
Just figured something out here.

1.0 was still outstarting the demo setup (minimal + dslam_navigation +
...). Need to run some tests with 1.0 to make sure this was the cause of
this issue. If it is the case, then the exception "device already locked"
would be correct -> 2x the same node tries to lock the USB/serial device.

On 2 January 2015 at 07:18, AlexReimann notifications@github.com wrote:

> It doesn't give an error code, it is just some ros nodes dying (during
> the start of minimal).
> On the second try everything works fine. Sometimes everything works on
> the first try (2 or 3 times out of 50).
> 
> I actually never saw it happen on gocart 1.1.
> There was no time for me to further investigate on wednesday because the
> reliability test had priority.
> 
> Am 02.01.2015 um 23:05 schrieb Daniel Stonier:
> 
> > Let me know what errno. shows if you see it - we can look up the man
> > page for |fcnt| to get the hint.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/stonier/ecl_core/issues/41#issuecomment-68528319.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stonier/ecl_core/issues/41#issuecomment-68533465.

## 

Innovation Team Leader
Yujin Robot
Seoul, Republic of Korea
Twitter: @yujinrobotinno
Website: http://inno.yujinrobot.com
Email: marcus.liebhardt@yujinrobot.com
Phone: +82-70-46577073

**Comment by stonier** [comment]
The posix error value will validate that.

**Comment by bit-pirate** [comment]
Haven't encounter this in a while now. Closing it. Re-open, if the issue reappears.
