### ISSUE TITLE
Compilation problem using ecl semaphores

### ISSUE THREAD

**Issue by MauroPagliarella** [stonier/ecl_core#43]
Compilation problem using ecl semaphores in ROS application. 

Hi all
For my robotics application running on ros I need to use a semaphore to manage the access to a shared data. I think I installed the ecl package but I'm not able to compile my application.
The command I used to install the packages is:   sudo apt-get install ros-indigo-ecl
and it has been executed without errors.

Any help is appreciated. Thank you very much.
Mauro

SYSTEM CONFIGURATION:
1: Laptop running Ubuntu 14.04 & ROS Indigo with the following packages installed in /opt/ros/indigo/share: 
...
1275458 drwxr-xr-x   2 root  4096 mag 23 18:09 ecl
1254917 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_build
1254887 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_command_line
1263061 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_concepts
1260072 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_config
1270681 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_containers
1263102 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_converters
1270944 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_converters_lite
1270942 drwxr-xr-x   2 root  4096 mag 22 22:45 ecl_core
1270930 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_core_apps
1270783 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_devices
1270812 drwxr-xr-x   4 root  4096 mag 22 22:45 ecl_eigen
1263075 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_errors
1263089 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_exceptions
1270653 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_formatters
1270838 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_geometry
1270955 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_io
1270862 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_ipc
1254875 drwxr-xr-x   4 root  4096 mag 22 22:45 ecl_license
1270820 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_linear_algebra
1270979 drwxr-xr-x   2 root  4096 mag 22 22:45 ecl_lite
1270994 drwxr-xr-x   2 root  4096 mag 22 22:45 ecl_manipulation
1270981 drwxr-xr-x   4 root  4096 mag 22 22:45 ecl_manipulators
1270828 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_math
1270998 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_mobile_robot
1263040 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_mpl
1271008 drwxr-xr-x   2 root  4096 mag 22 22:45 ecl_navigation
1270875 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_sigslots
1270967 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_sigslots_lite
1270935 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_statistics
1270890 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_streams
1270762 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_threads
1270736 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_time
1270714 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_time_lite
1271010 drwxr-xr-x   2 root  4096 mag 22 22:45 ecl_tools
1263051 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_type_traits
1270666 drwxr-xr-x   3 root  4096 mag 22 22:45 ecl_utilities
...

CODE IMPLEMENTATION:
1: 
## My test.h file contains:

...
# include <ecl/ipc/semaphore_pos.hpp>
# include <ecl/ipc/shared_memory_pos.hpp>

...
using ecl::Semaphore;
...
private:
    Semaphore    Sem;
## ...

2:
## My test.cpp file contains the following code in both the two functions which access the shared area:

void test_f() {
SemEncData.lock();
...
...
SemEncData.unlock();
## }

COMPILATION RESULTS:
During the compilation phase using   catkin_make --force-cmake  command, I get the following errors:

CMakeFiles/crawler.dir/src/encInterface.cpp.o: nella funzione "Enc::Enc(ros::NodeHandle_, int)":
encInterface.cpp:(.text+0x45[ 26%] ): riferimento non definito a "ecl::Semaphore::Semaphore()"
encInterface.cpp:(.text+0x6b):Built target server
 riferimento non definito a "ecl::Semaphore::unlock()"
encInterface.cpp:(.text+0x392): riferimento non definito a "ecl::Semaphore::~Semaphore()"
CMakeFiles/crawler.dir/src/encInterface.cpp.o: nella funzione "Enc::~Enc()":
encInterface.cpp:(.text+0x3fb): riferimento non definito a "ecl::Semaphore::~Semaphore()"
encInterface.cpp:(.text+0x43a): riferimento non definito a "ecl::Semaphore::~Semaphore()"
CMakeFiles/crawler.dir/src/encInterface.cpp.o: nella funzione "Enc::vCallback__GetEncData(boost::shared_ptr<std_msgs::Int32MultiArray_<std::allocator<void> > const> const&)":
encInterface.cpp:(.text+0x4a0): riferimento non definito a "ecl::Semaphore::lock()"
encInterface.cpp:(.text+0x531): riferimento non definito a "ecl::Semaphore::unlock()"
CMakeFiles/crawler.dir/src/encInterface.cpp.o: nella funzione "Enc::bGetEncData(int_)":
encInterface.cpp:(.text+0x577): riferimento non definito a "ecl::Semaphore::lock()"
encInterface.cpp:(.text+0x5b7): riferimento non definito a "ecl::Semaphore::unlock()"
CMakeFiles/crawler.dir/src/imuInterface.cpp.o: nella funzione "Imu::Imu(ros::NodeHandle_)":
imuInterface.cpp:(.text+0x3b): riferimento non definito a "ecl::Semaphore::Semaphore()"
imuInterface.cpp:(.text+0x76): riferimento non definito a "ecl::Semaphore::unlock()"
imuInterface.cpp:(.text+0x209): riferimento non definito a "ecl::Semaphore::~Semaphore()"
CMakeFiles/crawler.dir/src/imuInterface.cpp.o: nella funzione "Imu::~Imu()":
imuInterface.cpp:(.text+0x27f): riferimento non definito a "ecl::Semaphore::~Semaphore()"
imuInterface.cpp:(.text+0x2d5): riferimento non definito a "ecl::Semaphore::~Semaphore()"
CMakeFiles/crawler.dir/src/imuInterface.cpp.o: nella funzione "Imu::vCallback__GetImuData(boost::shared_ptr<sensor_msgs::Imu_<std::allocator<void> > const> const&)":
imuInterface.cpp:(.text+0x32e): riferimento non definito a "ecl::Semaphore::lock()"
imuInterface.cpp:(.text+0x4b6): riferimento non definito a "ecl::Semaphore::unlock()"
CMakeFiles/crawler.dir/src/imuInterface.cpp.o: nella funzione "Imu::bGetImuData(sensor_msgs::Imu_std::allocator<void >_)":
imuInterface.cpp:(.text+0x4e1): riferimento non definito a "ecl::Semaphore::lock()"
imuInterface.cpp:(.text+0x5f9): riferimento non definito a "ecl::Semaphore::unlock()"
collect2: error: ld returned 1 exit status
make[2]: **\* [/home/mauro/catkin/devel/lib/crawler/crawler] Errore 1
make[1]: **\* [crawler/CMakeFiles/crawler.dir/all] Errore 2
make[1]: **\* Attesa per i processi non terminati....
[ 26%] Built target vr0_generate_messages_cpp
make: **\* [all] Errore 2
Invoking "make -j2 -l2" failed

**Comment by MauroPagliarella** [comment]
Resolved!
It was due to my poor understanding of ROS. I forgot to update the find_package section in the CMakeLists.txt file in my catkin package with ecl_ipc reference. 

Mauro

**Comment by stonier** [comment]
Good to hear! :neckbeard:
