### ISSUE TITLE
Do you have a plan about jade release?

### ISSUE THREAD

**Issue by wkentaro** [stonier/ecl_core#47]
@stonier

**Comment by stonier** [comment]
Didn't have a plan, but can do. I'll update here once it's rolling.

**Comment by wkentaro** [comment]
In my workspace I have ecl packages. ( currently I'm using indigo)
I don't migrate to jade soon, but will do.
So if you release the ecl packages when you have time, it's really grateful.

**Comment by stonier** [comment]
Debs are on the [build farm](http://www.ros.org/debbuild/jade.html?q=ecl) in the shadow repo.

**Comment by wkentaro** [comment]
thanks :sparkles:
