### ISSUE TITLE
Could not find a package configuration file provided by "sophus"

### ISSUE THREAD

**Issue by wangzhaodong123** [stonier/ecl_core#57]
When i make my workspace,i met this problem,but there is sophus package in my workspace:
CMake Error at ecl_core/ecl_linear_algebra/CMakeLists.txt:22 (find_package):
  By not providing "Findsophus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "sophus", but
  CMake did not find one.

  Could not find a package configuration file provided by "sophus" with any
  of the following names:

    sophusConfig.cmake
    sophus-config.cmake

  Add the installation prefix of "sophus" to CMAKE_PREFIX_PATH or set
  "sophus_DIR" to a directory containing one of the above files.  If "sophus"
  provides a separate development package or SDK, be sure it has been
  installed.
Can you help me solve this problem?Thank you.

**Comment by stonier** [comment]
Did you install your rosdeps? It will have installed ros-kinetic-sophus (or other rosdistro) for you that way.

**Comment by wangzhaodong123** [comment]
It works,thanks for your help.

**Comment by Ankita-Singh-21** [comment]
Install sophus from source and extract it :       https://github.com/strasdat/Sophus.git
(rename sophus-master to sophus) and move it to /usr/local/include
sudo cmake ..
sudo make
(sudo make install)
