### ISSUE TITLE
Can a path be smoothed with a spline with this package?

### ISSUE THREAD

**Issue by omcandido** [stonier/ecl_core#59]
All examples have an increasing input vector X, like most implementations of spline calculators, as they are often conceived to smooth mathematical functions.

Can a random path be smoothed with these spline classes? i.e: can I input a pair of x_set and y_set vectors describing a spiral (`CubicSpline cubic = CubicSpline::Natural(x_set, y_set);`) and then retrieve the parameters of the spline at each point  _i_ (`cubic.polynomials()[i];`)?

**Comment by stonier** [comment]
Does constructing two splines over the same parameter set work for you? i.e.

```
CubicSpline cubic_x = CubicSpline::Natural(t_set, x_set);
CubicSpline cubic_y = CubicSpline::Natural(t_set, y_set);
```
