### ISSUE TITLE
error: ‘SE3Group’ does not name a type

### ISSUE THREAD

**Issue by techping** [stonier/ecl_core#63]
I build `ecl_core` package error in ROS lunar distribution...

```
In file included from ~/workspace/ros/catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra/sophus.hpp:20:0,
                 from ~/workspace/ros/catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra.hpp:20,
                 from ~/workspace/ros/catkin_ws/src/ecl_core/ecl_linear_algebra/src/lib/sophus_helpers.cpp:10:
~/workspace/ros/catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra/sophus/helpers.hpp:56:56: error: ‘SE3Group’ does not name a type

```

**Comment by techping** [comment]
Well, I see.
I should build [sophus](https://github.com/stonier/sophus) with ```indigo``` branch:
```shell
$ git checkout indigo
```

**Comment by stonier** [comment]
Sorry I missed this. Yes, indeed that is the case. The devel branch brought across recent development from upstream, but that can't be released to indigo/kinetic since that would break ABI for people that depend on it already. The devel branch will get released in the next long term release.
