### ISSUE TITLE
Build error ecl_math

### ISSUE THREAD

**Issue by pmwenzel** [stonier/ecl_core#65]
I tried to build `ecl_core` package in a ROS kinetic setup. Sophus branch is `release/0.9.1-kinetic`.

```
In file included from /root/ros_catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra/sophus.hpp:20:0,
                 from /root/ros_catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra.hpp:20,
                 from /root/ros_catkin_ws/src/ecl_core/ecl_linear_algebra/src/lib/sophus_interpolators.cpp:9:
/root/ros_catkin_ws/src/ecl_core/ecl_linear_algebra/include/ecl/linear_algebra/sophus/helpers.hpp:56:56: error: ‘SE3Group’ does not name a type
 std::ostream & operator << ( std::ostream & out, const SE3Group<T> & se3 )
```

Do you have any hints on this bug? Thanks.

**Comment by stonier** [comment]
I'd say that was the same as #63, but you shouldn't be seeing that with the `release/0.9.1-kinetic` branch.

**Comment by pmwenzel** [comment]
No, I build sophus from the `release/0.9.1-kinetic` branch and tried to build the `ecl_core` from the `release/0.61-indigo-kinetic` branch.

**Comment by stonier** [comment]
Ok, think I have it (my mistake). Delete and re-download the sophus `release/0.61-indigo-kinetic` branch. It should work now. Reopen if you still have problems.
