### ISSUE TITLE
ecl_debug_catch fails in release

### ISSUE THREAD

**Issue by stonier** [stonier/ecl_core#7]
```
ecl_debug_try {
    // something
ecl_debug_catch(Exception &e) { 
    std::cout << e.what() << std::endl;
}
```

is broken in release mode because it doesn't know what e is.

**Comment by stonier** [comment]
This is used liberally through the ycs. Should come up with a solution for it.

**Comment by bit-pirate** [comment]
The two cases I found are related with data writes on a "ecl::Serial`or`ftdi::Ftdi` instance and look like this:

```
ecl::Error PacketHandler::writeData(unsigned char *buff, unsigned long size_buff)
{
  ecl::Error error = ecl::NoError;
  if (device != NULL)
  {
    ecl_debug_try
    {
      if (device->write(buff, size_buff) == -1)
      {
        error = device->error(); // release mode and there is no exceptions, we land here.
      }
    }
    ecl_debug_catch (const ecl::StandardException &e){
      error = e.flag();
    }
  }
  else
  {
    error = ecl::NotInitialisedError;
  }
  return error;
}
```

I guess, it would be okay to just remove the exception handling until this gets properly fixed. Thoughts?

**Comment by stonier** [comment]
Sounds good to me - I still can't think of a way around this.

**Comment by clalancette** [comment]
@stonier For what it is worth, I just built all of ecl stuff locally in Release mode, and everything seems to work here.  So we might consider closing this very old bug.

**Comment by stonier** [comment]
Oh, that's interesting. I should leave bugs open more often, let the world fix my problems :)
