### ISSUE TITLE
warning: dynamic exception specifications are deprecated in C++11

### ISSUE THREAD

**Issue by lucascoelhof** [stonier/ecl_core#76]
Hi,

My package depends on ecl_geometry, and when I was trying to migrate from Indigo to Melodic, I got a lot of warnings regarding dynamic exception specifications, like this one:

> /opt/ros/melodic/include/ecl/exceptions/macros.hpp:120:44: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
>    #define ecl_assert_throw_decl(exception) throw(exception)
> /opt/ros/melodic/include/ecl/exceptions/macros.hpp:120:44: note: in definition of macro ‘ecl_assert_throw_decl’
> #define ecl_assert_throw_decl(exception) throw(exception)

I found a discussion in [StackOverflow](https://stackoverflow.com/questions/13841559/deprecated-throw-list-in-c11) about this issue.
I would suggest to change that, since it is deprecated.

**Comment by stonier** [comment]
Aha...building with defaults of catkin tools on melodic blocks you on this error.

I'll update shortly.

**Comment by stonier** [comment]
Released in melodic:

* ecl_core: https://github.com/stonier/ecl_core/pull/77 -> 0.62.2
* ecl_manipulation: https://github.com/stonier/ecl_manipulation/pull/5 -> 0.60.3

Also cherry-picked over to the ros2 `devel` branches.
