### ISSUE TITLE
error during install melodic version

### ISSUE THREAD

**Issue by benbenji** [stonier/ecl_core#82]
Hi  when I tried to install the melodic version of ecl_core the output shows that problem:
CMake Error at ecl_core/ecl_linear_algebra/CMakeLists.txt:29 (get_target_property):
get_target_property() called with non-existent target "Sophus::Sophus".
I use the melodic version of sophus 
did any gays meet this problem ? I will appreciate it very much if you can give me a solution

**Comment by stonier** [comment]
Did you use the binaries or the release branches (make sure you're not using the devel branches anywhere)?

**Comment by stonier** [comment]
Aging out.
