### ISSUE TITLE
Duplicate packages "ecl_mobile_robot" when compiling kobuki_core

### ISSUE THREAD

**Issue by josephkeem** [stonier/ecl_core#84]
Hello,

I'm trying to follow [this guide](https://yujinrobot.github.io/kobuki/enInstallationLinuxGuide.html) to compile/run the kobuki_driver C++ library without ROS on Ubuntu 18.04.2 LTS and I've run into an issue with `catkin_make_isolated --install`when trying to prepare the catkin workspace.

Here's the error that I'm getting when I run the command above:

    Base path: /home/josephkim/Desktop/csci370/swig_test/kobuki_core  
    Source space: /home/josephkim/Desktop/csci370/swig_test/kobuki_core/src  
    Build space: /home/josephkim/Desktop/csci370/swig_test/kobuki_core/build_isolated  
    Devel space: /home/josephkim/Desktop/csci370/swig_test/kobuki_core/devel_isolated  
    Install space: /home/josephkim/Desktop/csci370/swig_test/kobuki_core/install_isolated  
    WARNING: Metapackage "kobuki_core" must buildtool_depend on catkin.  
    WARNING: Metapackage "kobuki_core" should not have other dependencies besides a buildtool_depend on catkin and exec_depends.  
    Traceback (most recent call last):  
      File "/home/josephkim/Desktop/csci370/swig_test/kobuki_core/src/catkin/bin/catkin_make_isolated", line 160, in <module>  
        main()  
      File "/home/josephkim/Desktop/csci370/swig_test/kobuki_core/src/catkin/bin/catkin_make_isolated", line 156, in main  
        override_build_tool_check=opts.override_build_tool_check,  
      File "/home/josephkim/Desktop/csci370/swig_test/kobuki_core/src/catkin/bin/../python/catkin/builder.py", line 951, in build_workspace_isolated  
        packages = find_packages(sourcespace, exclude_subspaces=True)  
      File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 98, in find_packages  
        raise RuntimeError('\n'.join(duplicates))  
    RuntimeError: Multiple packages found with the same name "ecl_mobile_robot":  
    - ecl_core/ecl_mobile_robot  
    - ecl_navigation/ecl_mobile_robot

I'm not sure how to build and compile the driver library with this duplicate packages issue, and I'm not sure how to resolve this either.
Let me know if more specific information is needed; any help would be appreciated. Thanks!

**Comment by stonier** [comment]
Yujin isn't keeping the kobuki software up to date so there is some bit-rotting here and there.

To solve your problem though, if you're looking to build the ROS1 version of the software, make sure you pull from branches on the repositories for the melodic releases. e.g. for `ecl_core` pull `release/0.62-melodic` instead of devel. For `kobuki_core` pull `melodic` instead of `devel`.

Note: the error you saw was a migration on the devel branches of ecl to fold `ecl_navigation` back into `ecl_core`. It's a red herring if you're looking to build for ROS1, just get those melodic branches.

**Comment by stonier** [comment]
Closing this one out, but feel free to post questions here if you have them.

**Comment by josephkeem** [comment]
To get the kobuki_core library compiled, we gave up on using the tutorial linked in the OP. Instead, we downloaded the whole kobuki_core repo from github and the ecl-core, catkin, libusb-dev, and libftdi-dev debian packages, and compiled kobuki-core ourselves with catkin. This worked and allowed us to run the kobuki_core demo files on the Turtlebot2 without ROS.
