### ISSUE TITLE
exception on device open error - ecl_devices

### ISSUE THREAD

**Issue by yhju** [stonier/ecl_core#9]
When try to open serial device that already opened, ecl_devices throw the OpenError exception. It contains below information.

```
Location : /tmp/buildd/ros-groovy-ecl-devices-0.50.5-0precise-20130215-0822/src/lib/serial_pos.cpp:121 
Flag     : Could not open the requested object.
Detail   : Device is already locked. Try 'lsof | grep /dev/kobuki' to find other processes that currently have the port open.
```

but `lsof | grep /dev/kobuki` does not work for symbolic link. It should be `lsof | grep /dev/ttyUSB0` or similar.

**Comment by stonier** [comment]
d87eacd93da589f5c60402e5f35852a1927dfb28
